CREATE TABLE USUARIO(
USID int(3) NOT NULL AUTO_INCREMENT,
USUARIO VARCHAR(50) NULL,
TELEFONO VARCHAR(15) NULL,
DOMICILIO VARCHAR(100) NULL,
COMENTARIO  VARCHAR(200) NULL,
PRIMARY KEY (USID)
)

CREATE TABLE EMERGENCIA(
EID int(3) NOT NULL AUTO_INCREMENT,
USID int(3) NULL,
SID int(3) NULL,
LONGITUD VARCHAR(20) NULL,
LATITUD  VARCHAR(20) NULL,
ESTADO BIT(1),
COMENTARIOU  VARCHAR(200) NULL,
COMENTARIOS  VARCHAR(200) NULL,
IMAGEN BLOB,
PRIMARY KEY (EID),
INDEX(USID),
INDEX(SID),
FOREIGN KEY (USID)
REFERENCES USUARIO(USID)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (SID)
REFERENCES SERVICIO(SID)
ON DELETE CASCADE
ON UPDATE CASCADE
)

CREATE TABLE TSERVICIO(
TSID int(3) NOT NULL AUTO_INCREMENT,
DENOMINACION VARCHAR(50) NULL,
PRIMARY KEY (TSID)
)

CREATE TABLE SERVICIO(
SID int(3) NOT NULL AUTO_INCREMENT,
TSID int(3) NULL,
DENOMINACION VARCHAR(100) NULL,
DOMICILIO VARCHAR(100) NULL,
LATITUD VARCHAR(20) NULL, 
LONGITUD VARCHAR(20) NULL,
TELEFONO VARCHAR(15) NULL,
PRIMARY KEY (SID),
INDEX(TSID),
FOREIGN KEY (TSID)
REFERENCES TSERVICIO(TSID)
ON DELETE CASCADE
ON UPDATE CASCADE
)

